/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    '(2)': typeof import('./components/projects/ProjectListHeader - 副本 (2).vue')['default']
    '(3)': typeof import('./components/projects/ProjectListHeader - 副本 (3).vue')['default']
    '(4)': typeof import('./components/projects/ProjectListHeader - 副本 (4).vue')['default']
    '(5)': typeof import('./components/projects/ProjectListHeader - 副本 (5).vue')['default']
    '(6)': typeof import('./components/projects/ProjectListHeader - 副本 (6).vue')['default']
    '(7)': typeof import('./components/projects/ProjectListHeader - 副本 (7).vue')['default']
    '副本': typeof import('./components/projects/ProjectListHeader - 副本.vue')['default']
    BaseHeader: typeof import('./components/layouts/BaseHeader.vue')['default']
    BaseSide: typeof import('./components/layouts/BaseSide.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    ElTree: typeof import('element-plus/es')['ElTree']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Logos: typeof import('./components/Logos.vue')['default']
    MessageBoxDemo: typeof import('./components/MessageBoxDemo.vue')['default']
    ProjectCreateDialog: typeof import('./components/projects/ProjectCreateDialog.vue')['default']
    ProjectDetailHeader: typeof import('./components/projects/ProjectDetailHeader.vue')['default']
    ProjectEditDialog: typeof import('./components/projects/ProjectEditDialog.vue')['default']
    ProjectFileTreePanel: typeof import('./components/projects/ProjectFileTreePanel.vue')['default']
    ProjectFileViewer: typeof import('./components/projects/ProjectFileViewer.vue')['default']
    ProjectInfoCard: typeof import('./components/projects/ProjectInfoCard.vue')['default']
    ProjectListHeader: typeof import('./components/projects/ProjectListHeader.vue')['default']
    ProjectSearchResultPanel: typeof import('./components/projects/ProjectSearchResultPanel.vue')['default']
    ProjectSpecEditor: typeof import('./components/projects/ProjectSpecEditor.vue')['default']
    ProjectTable: typeof import('./components/projects/ProjectTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
